version: "3.9"

services:
  db:
    image: postgres
    shm_size: 700mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  goitpythonwebhw02:
    build: .
    container_name: goitpythonwebhw02_app
    ports:
      - 8000:8000
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data:
